### PR TITLE
Update to QtCreator 3.3

### PR DESCRIPTION
**Pull request by Typz**

### CODE REVIEW

**Comment by mloskot** [comment]
@Typz I'd started working on the big update, but failed to wrap my head around about the API changes between Qt Creator <=3.1 and >3.1. Your PR is a great help, awesome!

Hopefully, it addresses @jhunold's request in #8.
I will test it myself after the weekend.

**Comment by Typz** [comment]
I don't have lot of experience with boost::build, not sure everything is working well. But it seems to be OK so far, feel free to patch !

Also, it seems the "recommended" way to maintain plugins is to actually have them integrated into QtCreator source tree, would you mind going through that process?

**Comment by jhunold** [comment]
Thanks for the patch. It seems to be broken on QtCreator trunk, so the best solution really is to integrate it into QtCreator. Which only @mloskot can do. Though I can offer some help with gerrit et.al. if need arises.
@Typz could you please remove the whitespace changes from the patch? And please do not use tabs for indentation. It is good practise to follow the projects style which is space only indentation.

**Comment by Typz** [comment]
Sorry for the tabs, I just always forget to setup QtCreator when I open new project, and it unfortunately cannot figure out automatically how to follow the indent style... Anyway it's fixed now :-)

**Comment by mloskot** [comment]
The PR has been merged through @jhunold's #10 and published as qt-creator-3.3 branch for further testing.

Guys, once again, big thanks for your help

**Pull request closed without merging**
